
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: grpc
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

grpc:
  server:
    port: 9091
server:
  port: 8081